import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./styles/globals.css";
import { SessionProvider } from "next-auth/react";
import NavBar from './Components/navbar';


//the font used by the application unless otherwise specified
const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Target Tracking",
  description: "Generated by create next app",
};

//defines the root layout of the app
//wraps all pages with the global html structure and other shared UI
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${montserrat.variable} antialiased`}
      >
        <SessionProvider>
            <NavBar />
            {children}
        </SessionProvider>
      </body>
    </html>
  );
}
